### ISSUE TITLE
cpDNAExtraction/longRead/2_resultParse.py produce an empty file

### ISSUE THREAD

**Issue by agroppi** [asdcid/Chroloplast-genome-assembly#1]
I have run blasr (5.3) : 
```
blasr \
reads_pacbio_5kb.fastq \
ref_cp_double.fasta \
--nproc 20 \
--bestn 1 \
-m 1 \
--minMatch 15 \
--minAlnLength 5000 \
--out blasr_cp.out
```

But when I run getRead.py with : 
```
    inputFile   = 'blasr_cp.out'
    reference   = 'ref_cp_double.fasta'
    outputFile  = 'blasr_marouch_ref_cp_reads.fasta'
```

It produces an empty file without any error

**Comment by roblanf** [comment]
Hmmm. What's in your ref_cp_double.fasta file? I.e., do you expect that this will fish out your chloroplast reads? Typically, we use a bunch of doubled-up chloroplast genomes from close relatives.

**Comment by asdcid** [comment]
Sorry for the unclear name. The "reference" in this script should be the reads file (it is reads_pacbio_5kb.fastq in your case), not cp genome reference (ref_cp_double.fasta). I have changed the name "reference" to "reads", and added one more argument that  you need to input (the format of reads, fastq or fasta).

**Comment by agroppi** [comment]
I found the "bug"
Blasr (the version 5.3 I have used) add an string at the end of the read id
for example : 
read id in the fasta or fastq file : 
`m170322_065725_42263_c101114802550000001823258505011712_s1_p0/8/0_11197`

read id in the blasr output file : 
`m170322_065725_42263_c101114802550000001823258505011712_s1_p0/8/0_11197/0_5912`

I have parsed my blasr output file and deleted this additional string

Then your script works perfectly

**Comment by asdcid** [comment]
I will close this issue. If you have any other problems, feel free to reopen it.
