### ISSUE TITLE
Question : Post-assembly steps after hybrid protocol ?

### ISSUE THREAD

**Issue by agroppi** [asdcid/Chroloplast-genome-assembly#2]
My inputs : 
Pacbio reads and illumina reads
I have run all the steps of the hybrid-assembly protocol  until assembly.
But now the post assembly steps are unclear.
Can you be more specific, taking in account that I use Pacbio reads as Longreads and not ONT reads.

Thnaks you very much for your help

**Comment by asdcid** [comment]
Have you got the assembly result? how many contigs do you have? 

In general, if you only get one contig, that contig should be chloroplast genome. If three contigs, there should be LSC/SSC/IR, which means the length of long-read is not enough. If you have many contigs, it is better to align all contigs to other chloroplast genome using mummer and plot it to see what happened. 

1.You can use mummer to do the alignment, and plot the figure to see whether it is a good chloroplast genome. 
2. Unicycler has already polished your genome, if you use default setting. I don't think you need to polish it again if you get the whole cp genome from the Unicycler result. If you want to polish your genome again, just use illumina reads, we find it is not necessary to polish the genome using long-reads. 
3. You can remap the illumina reads to check the mapping rate and error rate.
4. The Pacbio reads can be used for SNP calls, but my script only works for SNP calls using ONT reads.

**Comment by agroppi** [comment]
For two different species the pipeline worked very well.
I have only one contig.
Taking in account your explanations, I assume I can skip the steps of post assembly and move to the phylogenetic_analysis step
Thanks again.

**Comment by asdcid** [comment]
No worries.
